name: Deploy Image CI Release
on:
  push:
    tags:
      - "*"
concurrency:
  group: "docker-image"
  cancel-in-progress: true
env:
  DOCKER_BUILDKIT: "1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          build-args: |
            VERSION=latest
      - name: GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          release_name: v${{ github.ref_name }}
          body_path: CHANGELOG.md
